### ISSUE TITLE
Missing "use" in lib.rs with generated class at path

### ISSUE THREAD

**Issue by Zennii** [macalimlim/ftw#16]
I ran `ftw class chars/Player KinematicBody` but when I tried to run the whole game (`ftw run`), Rust gave an error that it couldn't find `player` in `handle.add_class::<player::Player>();`. This seemed to be because the generated code added `mod chars;` to the top, but not `use chars::*;` or at least `use chars::player;` and I had to add it myself.

I'm using the released ftw 0.6.0

**Comment by macalimlim** [comment]
Hi @Zennii, thankyou for filing this issue. I will take a look at it this week.

**Comment by macalimlim** [comment]
Can you give me more details about your setup? Like godot-rust version, operating system, etc. Did you generate the project using `ftw new <project>`? Or using the cargo-generate template from a previous version? Thanks

**Comment by macalimlim** [comment]
I did some local testing and I did not get the same error. Please see the attached screenshot 
![ftw-github-issue-16](https://user-images.githubusercontent.com/5382992/123572481-e21abc00-d7fe-11eb-969c-0edc483e2c0f.png)

**Comment by macalimlim** [comment]
The ftw version I used in the screenshot above is the latest on the main branch. The next screenshot is the ftw version that is being distributed by crates.io 
![ftw-github-issue-16-p2](https://user-images.githubusercontent.com/5382992/123573168-03c87300-d800-11eb-9d19-ff927c69be49.png)

**Comment by macalimlim** [comment]
In both cases, I did not get the same error as you did, can you give me more details about your setup?

**Comment by Zennii** [comment]
I did generate it using `ftw new <project>`, I'm using Windows 10, Cargo.toml says `gdnative = "0.9.3"`, it happens every time I create a new class, I have to add the imports for every single class each time. If rust version helps: `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

**Comment by Zennii** [comment]
For example, creating a random class (`chars/Playertt`) just now:
![image](https://user-images.githubusercontent.com/18521883/123887567-c22ee980-d91f-11eb-9c07-1623280e66b4.png)
Red shows the errors (Clion), it generates with incorrect pathing or missing necessary imports

```
use cams::mouse_cam_clipped;
use chars::{player, playertt};
```

**Comment by Zennii** [comment]
![image](https://user-images.githubusercontent.com/18521883/123888017-98c28d80-d920-11eb-8170-fbbd58c87601.png)
I performed the same steps as one of your screenshots in powershell and it seems to have replicated the problem

**Comment by macalimlim** [comment]
@Zennii please see the [PR](https://github.com/macalimlim/ftw/pull/17) for this issue

**Comment by Zennii** [comment]
@macalimlim Looks like that branch fixes it for me as well! Thanks!

![image](https://user-images.githubusercontent.com/18521883/124191121-52407080-da91-11eb-859e-86cfbbf16616.png)

**Comment by macalimlim** [comment]
Great! I will do a release these coming days. Thanks again for filing this issue 👍🏾
