### ISSUE TITLE
Add ability to create tool scripts

### ISSUE THREAD

**Issue by aclave1** [macalimlim/ftw#21]
Currently, FTW supports creating regular classes and singletons using the `class` and `singleton` commands. I propose adding another command `tool`. 

Currently, ftw overwrites the lib.rs file and the `init` function. This means that custom `handle.add_class<>` calls are removed from the file. In order to register a tool script with godot-rust, you have to do something like
```
fn init(handle: InitHandle) {
  handle.add_tool_class::<MyClass>();
}
```

but this will be overwritten if you ever run a command like `ftw class` again.

I tried implementing this command, but I got stuck because the current implementation reads the source-dir and looks for [NativeClass] using a regex. I couldn't think of a good approach for tool scripts so I decided to post an issue here and get some feedback from you before I proceed. For example, I thought of adding some custom attribute, but this would require users to import a crate into their project which feels messy and against the current approach. I also thought of making the user add a comment but this approach is not always popular.

Another option, instead of implementing this tool command, is some workaround that allows you to call some custom code from the lib.rs file.

**Comment by macalimlim** [comment]
Hi @aclave1 

Please check this PR #22. If you have any comments and/or suggestions, please let me know.

Mike

**Comment by macalimlim** [comment]
Also, please check the updated README for creating the tool class.

**Comment by aclave1** [comment]
@macalimlim thanks for implementing that!
