### ISSUE TITLE
provide a way to customize which godot binary

### ISSUE THREAD

**Issue by macalimlim** [macalimlim/ftw#9]
provide a way to customize which godot binary to be used to invoke commands that use godot. For example, instead of having `godot` binary on $PATH,  I want to have a custom batch or shell script file to invoke godot...

**Comment by Bromeon** [comment]
If it expects `godot` (not `godot.exe`) to be in PATH, that should probably be documented. And maybe the error can be caught by Rust and printed? The Windows error says something along "file specified cannot be found" without mentioning the file name, which is pretty annoying 🙂

**Comment by macalimlim** [comment]
It is documented [here](https://github.com/godot-rust/godot-rust-template/wiki#on-windows). Yeah I do agree with you about not being specific on what error is happening...
